### ISSUE TITLE
Fails to build on pkg-build.racket-lang.org

### ISSUE THREAD

**Issue by samth** [mordae/racket-libscrypt#1]
Probably this is because of the examples in the documentation. You can use http://docs.racket-lang.org/unstable/sandbox.html#%28def._%28%28lib._unstable%2Fsandbox..rkt%29._make-log-based-eval%29%29 to produce an evaluator where you don't actually need scrypt on the machine.

**Comment by mordae** [comment]
Thanks for the tip.
